/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/YxCFcoFWaqr
 */
import { Avatar } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Chat() {
  return (
    <div className="grid w-full max-w-2xl grid-rows-auto gap-4 px-4">
      <div className="flex items-center space-x-4">
        <Avatar className="w-10 h-10" />
        <div className="space-y-1">
          <h1 className="text-lg font-medium leading-none">GPT-4</h1>
          <p className="text-sm leading-none text-gray-500 dark:text-gray-400">Typing</p>
        </div>
      </div>
      <div className="grid grid-cols-2 gap-4">
        <div className="flex items-end space-x-4 col-start-1 col-end-3">
          <div className="grid grid-rows-auto gap-2">
            <div className="p-2 rounded-lg bg-gray-100 dark:bg-gray-800">
              Hi there! How can I assist you today?
              <div className="text-xs leading-none mt-1 text-gray-500 dark:text-gray-400">2 minutes ago</div>
            </div>
            <div className="p-2 rounded-lg bg-gray-100 dark:bg-gray-800">
              Could you provide me with more details?
              <div className="text-xs leading-none mt-1 text-gray-500 dark:text-gray-400">1 minute ago</div>
            </div>
          </div>
          <Avatar className="w-8 h-8 order-2" />
        </div>
      </div>
      <div className="flex w-full items-center space-x-4">
        <div className="w-full">
          <Input placeholder="Type a message" />
        </div>
        <Button>Send</Button>
      </div>
    </div>
  )
}
